### ISSUE TITLE
Missing characters

### ISSUE THREAD

**Issue by Blaz-IN-ferno** [winsomniak/kagero-calc#104]
“Marisa: Crimson Flash”, and “Corrin: Enjoying Tradition” are missing from the max defense chart.

**Comment by winsomniak** [comment]
Yeah, the main KageroChart site is way behind. Unfortunately time-poor right now, but an update is coming with the missing hero pages and statistics.

About to release an update for the damage calc and some stylistic improvements.

Closing this since the board is technically for the damage-calc only. Thanks for reporting!
