### ISSUE TITLE
Community Update

### ISSUE THREAD

**Issue by Lorenzooone** [winsomniak/kagero-calc#75]
The testing setup (BTW, thanks a LOT for sharing it) doesn't seem to use the data from the local data folder... Could this be fixed? I'll try doing it myself once I'm back from swimming, but, if I won't be able to figure it out, some help would be appreciated.

Edit: Init.js is the culprit

**Comment by winsomniak** [comment]
Ah I forgot to make a note of this!

The calc pulls **all** data from the live version of KageroChart currently.
KageroChart concthe data from the calc as part of the response.

Its not ideal after opening up the source, because its harder for 3rd
parties to test. I need to do a bit off design work on this, as my intent
was for KageroChart and the calc to use the same datasource.

If you'd like to take a temporary measure, just change init.js to load from
a static file instead of https://kagerochart.com/data. Just be aware that I
may need to modify this behavior in the coming weeks.

**Comment by winsomniak** [comment]
Ah I forgot to make a note of this!

The calc pulls **all** data from the live version of KageroChart currently.
KageroChart concatenates /data from the calc as part of the response.

This is not ideal after opening up the source, because its harder for 3rd
parties to test without database access. I need to do a bit off design work
on this, as my intent was for KageroChart and the calc to use the same
datasource.

If you'd like to take a temporary measure, just change init.js to load from
a static file instead of https://kagerochart.com/data and make changes
locally to the static file. Just be aware that I may need to modify this
behavior in the coming weeks.

Cheers
